FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY apps/worker/package.json ./apps/worker/
COPY packages/db/package.json ./packages/db/

RUN npm install --workspaces --include-workspace-root

COPY packages/db ./packages/db
RUN cd packages/db && npx prisma generate

COPY apps/worker ./apps/worker

CMD ["node", "apps/worker/src/index.js"]
