version: '3.8'

services:
  # Judge0 dependencies
  judge0-db:
    image: postgres:13
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0secret
    volumes:
      - judge0-db-data:/var/lib/postgresql/data

  judge0-redis:
    image: redis:6.0

  # Judge0 CE server
  judge0-server:
    image: judge0/judge0:1.13.1
    ports:
      - '2358:2358'
    depends_on:
      - judge0-db
      - judge0-redis
    env_file:
      - ./judge0.conf
    privileged: true
    restart: on-failure

  # Judge0 CE workers
  judge0-workers:
    image: judge0/judge0:1.13.1
    command: ['./scripts/workers']
    depends_on:
      - judge0-db
      - judge0-redis
    env_file:
      - ./judge0.conf
    privileged: true
    restart: on-failure

  # Our API
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - '4001:4000'
    env_file:
      - ../.env
    environment:
      - JUDGE0_URL=http://judge0-server:2358
      - WEB_URL=http://localhost:3000
      - NODE_ENV=development
    depends_on:
      - judge0-server
    restart: on-failure

  # Our Worker
  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    env_file:
      - ../.env
    environment:
      - JUDGE0_URL=http://judge0-server:2358
      - NODE_ENV=development
    depends_on:
      - judge0-server
    restart: on-failure

  # Our Web (Next.js)
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - '8080:3000'
    environment:
      - API_URL=http://api:4000
      - HOSTNAME=0.0.0.0
    depends_on:
      - api
    restart: on-failure

volumes:
  judge0-db-data:

